function getDati() {
    let out = [
        {persona: "Lorenzo", materia: "Istituzioni di Logica", aula: "Aula 3A", edificio: "Sa Duchessa", giorno: "Lunedì", inizio: "11:40", fine: "13:05"},
        {persona: "Lorenzo", materia: "Ingegneria del Software", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Martedì", inizio: "9:00", fine: "10:45"},
        {persona: "Lorenzo", materia: "Ingegneria del Software Ex", aula: "Laboratorio T", edificio: "Palazzo delle Scienze", giorno: "Martedì", inizio: "11:00", fine: "13:00"},
        {persona: "Lorenzo", materia: "Ingegneria del Software", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Mercoledì", inizio: "9:00", fine: "10:45"},
        {persona: "Lorenzo", materia: "Istituzioni di Logica", aula: "Aula 17", edificio: "Sa Duchessa", giorno: "Mercoledì", inizio: "11:40", fine: "13:05"},
        {persona: "Lorenzo", materia: "Calcolo Scientifico e Metodi Numerici", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Mercoledì", inizio: "15:00", fine: "16:45"},
        {persona: "Lorenzo", materia: "Istituzioni di Logica", aula: "Aula 17", edificio: "Sa Duchessa", giorno: "Venerdì", inizio: "9:15", fine: "10:50"},
        {persona: "Lorenzo", materia: "Calcolo Scientifico e Metodi Numerici Ex", aula: "Laboratorio T", edificio: "Palazzo delle Scienze", giorno: "Venerdì", inizio: "11:30", fine: "13:15"},
        {persona: "Vargiu", materia: "Matematica Discreta", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Lunedì", inizio: "9:00", fine: "10:45"},
        {persona: "Vargiu", materia: "Fisica e Metodo Scientifico", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Lunedì", inizio: "11:00", fine: "12:45"},
        {persona: "Vargiu", materia: "Matematica Discreta", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Martedì", inizio: "11:00", fine: "12:45"},
        {persona: "Vargiu", materia: "Algoritmi e Strutture Dati", aula: "Aula F / Laboratorio T", edificio: "Palazzo delle Scienze", giorno: "Martedì", inizio: "15:00", fine: "17:30"},
        {persona: "Vargiu", materia: "Matematica Discreta", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Mercoledì", inizio: "11:00", fine: "12:45"},
        {persona: "Vargiu", materia: "Algoritmi e Strutture Dati", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Giovedì", inizio: "9:00", fine: "10:45"},
        {persona: "Vargiu", materia: "Architettura degli Elaboratori", aula: "Aula Magna di Matematica", edificio: "Palazzo delle Scienze", giorno: "Giovedì", inizio: "11:00", fine: "13:30"},
        {persona: "Vargiu", materia: "Algoritmi e Strutture Dati", aula: "Aula Costa", edificio: "Aula Costa", giorno: "Venerdì", inizio: "9:00", fine: "10:45"},
        {persona: "Vargiu", materia: "Architettura degli Elaboratori", aula: "Aula Costa", edificio: "Aula Costa", giorno: "Venerdì", inizio: "11:00", fine: "12:45"},
        {persona: "Alessio", materia: "Tedesco 3 Ex", aula: "Aula 3", edificio: "Campus Aresu", giorno: "Lunedì", inizio: "11:40", fine: "13:10"},
        {persona: "Alessio", materia: "Tedesco 3 Ex", aula: "Aula 3", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "16:25", fine: "17:55"},
        {persona: "Alessio", materia: "Inglese 3 Ex", aula: "Aula Magna", edificio: "Campus Aresu", giorno: "Lunedì", inizio: "16:25", fine: "17:55"},
        {persona: "Alessio", materia: "Inglese 3 Ex", aula: "Aula 2", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "14:50", fine: "16:20"},
        {persona: "Alessio", materia: "Mediazione Orale Tedesca", aula: "Aula 11", edificio: "Campus Aresu", giorno: "Martedì", inizio: "16:25", fine: "17:55"},
        {persona: "Alessio", materia: "Mediazione Orale Tedesca", aula: "Aula 11", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "13:10", fine: "14:45"},
        {persona: "Alessio", materia: "Mediazione Orale Tedesca", aula: "Aula 6", edificio: "Campus Aresu", giorno: "Giovedì", inizio: "11:40", fine: "13:10"},
        {persona: "Swami", materia: "Cinema e Storia", aula: "Aula 4", edificio: "Campus Aresu", giorno: "Lunedì", inizio: "8:30", fine: "10:00"},
        {persona: "Swami", materia: "Communication and Social Media", aula: "Aula 7", edificio: "Campus Aresu", giorno: "Lunedì", inizio: "18:00", fine: "19:30"},
        {persona: "Swami", materia: "Cinema e Storia", aula: "Aula 6", edificio: "Campus Aresu", giorno: "Martedì", inizio: "8:30", fine: "10:00"},
        {persona: "Swami", materia: "Laboratorio Cinese Ex", aula: "Laboratorio 1", edificio: "Campus Aresu", giorno: "Martedì", inizio: "10:05", fine: "11:35"},
        {persona: "Swami", materia: "Sociologia dei Processi Comunicativi", aula: "Aula 4", edificio: "Campus Aresu", giorno: "Martedì", inizio: "11:40", fine: "13:10"},
        {persona: "Swami", materia: "Sociologia dei Processi Comunicativi", aula: "Aula 4", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "8:30", fine: "10:00"},
        {persona: "Swami", materia: "Laboratorio Cinese Ex", aula: "Aula 2", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "10:05", fine: "11:35"},
        {persona: "Swami", materia: "Inglese Ex", aula: "Laboratorio C", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "11:40", fine: "13:10"},
        {persona: "Swami", materia: "Communication and Social Media", aula: "Aula 7", edificio: "Campus Aresu", giorno: "Mercoledì", inizio: "14:50", fine: "16:20"},
        {persona: "Swami", materia: "Inglese Ex", aula: "Aula 11", edificio: "Campus Aresu", giorno: "Giovedì", inizio: "8:30", fine: "10:00"},
        {persona: "Swami", materia: "Laboratorio Cinese", aula: "Aula 4", edificio: "Campus Aresu", giorno: "Giovedì", inizio: "10:05", fine: "11:35"},
        {persona: "Swami", materia: "Cinema e Storia", aula: "Aula 4", edificio: "Campus Aresu", giorno: "Venerdì", inizio: "8:30", fine: "10:00"},
    ];
    return out;
}
