(// TODO: aggiungere campo "edificio" e rimuovere l'inferenza dal nome dell'aula
// TODO: aggiornare i dati di Swami
// TODO: aggiungere supporto per le lezioni opzionali

function getDati() {
    let out = [
        {persona: "Lorenzo",materia: "Interazione Uomo-Macchina",aula: "Aula Magna di Matematica",giorno: "Lunedì",inizio: 132,fine: 153},
        {persona: "Lorenzo",materia: "Interazione Uomo-Macchina Ex",aula: "Laboratorio T",giorno: "Lunedì",inizio: 174,fine: 204},
        {persona: "Lorenzo",materia: "Basi di Dati",aula: "Aula Magna di Matematica",giorno: "Martedì",inizio: 108,fine: 129},
        {persona: "Lorenzo",materia: "Basi di Dati Ex",aula: "Laboratorio T",giorno: "Martedì",inizio: 132,fine: 162},
        {persona: "Lorenzo",materia: "Basi di Dati",aula: "Aula Magna di Matematica",giorno: "Mercoledì",inizio: 108,fine: 129},
        {persona: "Lorenzo",materia: "Linguaggi di Programmazione",aula: "Aula Magna di Matematica",giorno: "Mercoledì",inizio: 132,fine: 153},
        //{persona: "Lorenzo",materia: "Linguaggi di Programmazione Ex",aula: "Laboratorio T",giorno: "Mercoledì",inizio: 174,fine: 204},
        {persona: "Lorenzo",materia: "Linguaggi di Programmazione",aula: "Aula Magna di Matematica",giorno: "Giovedì",inizio: 108,fine: 129},
        {persona: "Lorenzo",materia: "Linguaggi di Programmazione Ex",aula: "Laboratorio T",giorno: "Giovedì",inizio: 132,fine: 162},
        {persona: "Swami",materia: "Storia e Critica del Cinema",aula: "Aula 5",edificio: "Sa Duchessa",giorno: "Lunedì",inizio: "15:45",fine: "17:15"},
        {persona: "Swami",materia: "Laboratorio Cinese Ex",aula: "Laboratorio 1",giorno: "Martedì",inizio: 121,fine: 139},
        {persona: "Swami",materia: "Inglese Ex",aula: "Aula 11",giorno: "Martedì",inizio: 140,fine: 158},
        {persona: "Swami",materia: "English Language and Communication Skills",aula: "Aula 7",giorno: "Martedì",inizio: 158,fine: 177},
        {persona: "Swami",materia: "Storia e Critica del Cinema",aula: "Aula 6", edificio:"Sa Duchessa",giorno: "Martedì",inizio: "15:45",fine: "17:15"},
        {persona: "Swami",materia: "Laboratorio Cinese Ex",aula: "Aula 2",giorno: "Mercoledì",inizio: 121,fine: 139},
        {persona: "Swami",materia: "Inglese Ex",aula: "Laboratorio Lingue A1",giorno: "Mercoledì",inizio: 140,fine: 158},
        {persona: "Swami",materia: "English Language and Communication Skills",aula: "Aula 7",giorno: "Mercoledì",inizio: 158,fine: 177},
        {persona: "Swami",materia: "Linguaggi dello Spettacolo",aula: "Aula 9",giorno: "Mercoledì",inizio: 178,fine: 196},
        {persona: "Swami",materia: "Linguaggi della Televisione e dei Nuovi Media",aula: "Aula 2", edificio:"Campus Aresu",giorno: "Giovedì",inizio: "13:10",fine: "14:45"},
        {persona: "Swami",materia: "Storia e Critica del Cinema",aula: "Aula 6",edificio:"Sa Duchessa",giorno: "Giovedì",inizio: "14:05",fine: "15:35"},
        {persona: "Swami",materia: "Linguaggi della Televisione e dei Nuovi Media",aula: "Aula 2", edificio:"Campus Aresu",giorno: "Venerdì",inizio: "14:50",fine: "16:20"},
        {persona: "Alessio",materia: "Tedesco 3 Ex",aula: "Aula 3",giorno: "Lunedì",inizio: 140,fine: 158},
        {persona: "Alessio",materia: "Inglese 3 Ex",aula: "Aula Magna",giorno: "Lunedì",inizio: 197,fine: 215},
        {persona: "Alessio",materia: "Filologia Germanica",aula: "Aula 11",giorno: "Martedì",inizio: 121,fine: 139},
        {persona: "Alessio",materia: "Tedesco 3 Ex",aula: "Aula 3",giorno: "Martedì",inizio: 178,fine: 196},
        {persona: "Alessio",materia: "Mediazione Orale Inglese",aula: "Aula 8",giorno: "Mercoledì",inizio: 140,fine: 158},
        {persona: "Alessio",materia: "Inglese 3",aula: "Aula Magna",giorno: "Mercoledì",inizio: 158,fine: 177},
        {persona: "Alessio",materia: "Inglese 3 Ex",aula: "Aula 7",giorno: "Mercoledì",inizio: 178,fine: 196},
        {persona: "Alessio",materia: "Tedesco 3 Ex",aula: "Aula 3",giorno: "Mercoledì",inizio: 197,fine: 215},
        {persona: "Alessio",materia: "Filologia Germanica",aula: "Aula 11",giorno: "Giovedì",inizio: 121,fine: 139},
        {persona: "Alessio",materia: "Tedesco 3",aula: "Aula 9",giorno: "Giovedì",inizio: 140,fine: 158},
        {persona: "Alessio",materia: "Inglese 3 Ex",aula: "Laboratorio Lingue A1",giorno: "Giovedì",inizio: 197,fine: 215},
        {persona: "Alessio",materia: "Mediazione Orale Inglese",aula: "Didattica a Distanza",giorno: "Venerdì",inizio: 197,fine: 215},
        {persona: "Alessio",materia: "Mediazione Orale Inglese",aula: "Didattica a Distanza",giorno: "Venerdì",inizio: 216,fine: 234},
        {persona: "Vargiu",materia: "Programmazione 1",aula: "Aula Costa",giorno: "Lunedì",inizio: 174,fine: 195},
        {persona: "Vargiu",materia: "Fondamenti di Informatica",aula: "Aula Costa",giorno: "Lunedì",inizio: 198,fine: 219},
        {persona: "Vargiu",materia: "Analisi Matematica",aula: "Aula Costa",giorno: "Martedì",inizio: 108,fine: 129},
        {persona: "Vargiu",materia: "Programmazione 1 Ex",aula: "Laboratorio T",giorno: "Martedì",inizio: 174,fine: 204},
        {persona: "Vargiu",materia: "Fondamenti di Informatica",aula: "Aula Costa",giorno: "Mercoledì",inizio: 174,fine: 195},
        {persona: "Vargiu",materia: "Analisi Matematica",aula: "Aula Costa",giorno: "Giovedì",inizio: 132,fine: 153},
        {persona: "Vargiu",materia: "Programmazione 1 Ex",aula: "Laboratorio T",giorno: "Giovedì",inizio: 174,fine: 204},
        {persona: "Vargiu",materia: "Programmazione 1",aula: "Aula Costa",giorno: "Venerdì",inizio: 108,fine: 129},
        {persona: "Vargiu",materia: "Analisi Matematica",aula: "Aula Costa",giorno: "Venerdì",inizio: 132,fine: 153},
        {persona: "Zanzu",materia: "Fisica 2",aula: "L_TB - Aula Z",giorno: "Lunedì",inizio: 126,fine: 150},
        {persona: "Zanzu",materia: "Scienza delle Costruzioni",aula: "L_TB - Aula Z",giorno: "Lunedì",inizio: 150,fine: 162},
        {persona: "Zanzu",materia: "Scienza delle Costruzioni",aula: "D1_TA - Aula DIGITA",giorno: "Martedì",inizio: 114,fine: 138},
        {persona: "Zanzu",materia: "Fisica 2",aula: "L_TA - Aula V",giorno: "Martedì",inizio: 138,fine: 162},
        {persona: "Zanzu",materia: "Analisi Matematica 2",aula: "L_TB - Aula Z",giorno: "Martedì",inizio: 180,fine: 204},
        {persona: "Zanzu",materia: "Fisica Tecnica Ambientale",aula: "I_1E - Aula L",giorno: "Martedì",inizio: 204,fine: 228},
        {persona: "Zanzu",materia: "Scienza delle Costruzioni",aula: "I_1D - Aula M",giorno: "Mercoledì",inizio: 102,fine: 126},
        {persona: "Zanzu",materia: "Fisica 2",aula: "L_TB - Aula Z",giorno: "Mercoledì",inizio: 126,fine: 162},
        {persona: "Zanzu",materia: "Analisi Matematica 2",aula: "L_TB - Aula Z",giorno: "Mercoledì",inizio: 180,fine: 216},
        {persona: "Zanzu",materia: "Scienza delle Costruzioni",aula: "D1_TA - Aula DIGITA",giorno: "Giovedì",inizio: 126,fine: 162},
        {persona: "Zanzu",materia: "Fisica Tecnica Ambientale",aula: "D1_TA - Aula DIGITA",giorno: "Giovedì",inizio: 180,fine: 204},
        {persona: "Zanzu",materia: "Fisica Tecnica Ambientale",aula: "I_1D - Aula M",giorno: "Venerdì",inizio: 102,fine: 126},
        {persona: "Zanzu",materia: "Analisi Matematica 2",aula: "I_TA - Aula CD",giorno: "Venerdì",inizio: 126,fine: 162},
        {persona: "Giacomo",materia: "Inglese 2 Ex",aula: "Laboratorio C",giorno: "Lunedì",inizio: 102,fine: 120},
        {persona: "Giacomo",materia: "Letteratura Inglese 1",aula: "Aula 7",giorno: "Lunedì",inizio: 121,fine: 139},
        {persona: "Giacomo",materia: "Letteratura Spagnola 1",aula: "Aula Magna",giorno: "Lunedì",inizio: 140,fine: 158},
        {persona: "Giacomo",materia: "Inglese 2",aula: "Aula Magna",giorno: "Lunedì",inizio: 158,fine: 177},
        {persona: "Giacomo",materia: "Spagnolo 2 Ex",aula: "Laboratorio C",giorno: "Lunedì",inizio: 197,fine: 215},
        {persona: "Giacomo",materia: "Teoria e Storia della Traduzione 1",aula: "Aula Magna",giorno: "Lunedì",inizio: 216,fine: 234},
        {persona: "Giacomo",materia: "Inglese 2 Ex",aula: "Aula 7",giorno: "Martedì",inizio: 121,fine: 139},
        {persona: "Giacomo",materia: "Letteratura Spagnola 1",aula: "Aula 3",giorno: "Martedì",inizio: 140,fine: 158},
        {persona: "Giacomo",materia: "Letteratura Spagnola 1",aula: "Aula 7",giorno: "Mercoledì",inizio: 102,fine: 120},
        {persona: "Giacomo",materia: "Spagnolo 2 Ex",aula: "Aula 2",giorno: "Mercoledì",inizio: 158,fine: 177},
        {persona: "Giacomo",materia: "Inglese 2 Ex",aula: "Aula 3",giorno: "Mercoledì",inizio: 178,fine: 196},
        {persona: "Giacomo",materia: "Letteratura Inglese 1",aula: "Aula 7",giorno: "Mercoledì",inizio: 197,fine: 215},
        {persona: "Giacomo",materia: "Letteratura Inglese 1",aula: "Aula 7",giorno: "Venerdì",inizio: 121,fine: 139},
        {persona: "Giacomo",materia: "Spagnolo 2 Ex",aula: "Laboratorio C",giorno: "Venerdì",inizio: 197,fine: 215},
        {persona: "Davide",materia: "Sistemi Operativi Ex",aula: "Laboratorio T",giorno: "Lunedì",inizio: 204,fine: 234},
        {persona: "Davide",materia: "Automi e Linguaggi Formali",aula: "Aula Magna di Matematica",giorno: "Martedì",inizio: 132,fine: 153},
        {persona: "Davide",materia: "Sistemi Operativi",aula: "Aula Magna di Matematica",giorno: "Martedì",inizio: 174,fine: 195},
        {persona: "Davide",materia: "Sistemi Operativi Ex",aula: "Laboratorio T",giorno: "Mercoledì",inizio: 135,fine: 165},
        {persona: "Davide",materia: "Sistemi Operativi",aula: "Aula Magna di Matematica",giorno: "Mercoledì",inizio: 174,fine: 195},
        {persona: "Davide",materia: "Automi e Linguaggi Formali",aula: "Aula Magna di Matematica",giorno: "Giovedì",inizio: 132,fine: 153},
        {persona: "Davide",materia: "Dati e Modelli",aula: "Aula Magna di Matematica",giorno: "Giovedì",inizio: 174,fine: 195},
        {persona: "Davide",materia: "Diritto",aula: "Aula Magna di Matematica",giorno: "Giovedì",inizio: 195,fine: 216},
        {persona: "Davide",materia: "Automi e Linguaggi Formali",aula: "Aula Magna di Matematica",giorno: "Venerdì",inizio: 132,fine: 153},
        {persona: "Davide",materia: "Dati e Modelli",aula: "Aula Magna di Matematica",giorno: "Venerdì",inizio: 174,fine: 195},
        {persona: "Davide",materia: "Diritto",aula: "Aula Magna di Matematica",giorno: "Venerdì",inizio: 195,fine: 216},

    ];
    return out;
}
